name: zed-package

on:
  pull_request:
    paths:
      - ".zpkg.toml"
      - ".zpkg.lock"
      - ".gitignore"
      - ".github/workflows/zed-package.yml"
  push:
    branches: [main]
    paths:
      - ".zpkg.toml"
      - ".zpkg.lock"
      - ".gitignore"
      - ".github/workflows/zed-package.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: zed-pkg/zed-interfaces/.github/workflows/validate-zed-package.yml@169e599646a75d874c3ec0351d3088b4f86aaca2
