name: zed-package

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - ".zpkg.toml"
      - ".zpkg.lock"
      - ".gitignore"
      - ".github/workflows/zed-package.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  certify:
    uses: zed-pkg/zed-interfaces/.github/workflows/certify-zed-package.yml@0b1ded0c6470f533ca3359dc3e104437c9b5bdc9
