name: zed-package

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - ".zpkg.toml"
      - ".zpkg.lock"
      - ".gitignore"
      - ".github/workflows/zed-package.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  certify:
    uses: zed-pkg/zed-interfaces/.github/workflows/certify-zed-package.yml@1f77011287e8d7449da7dab6a23f2b71118a5137
